name: mapsuygulama
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.2
  url_launcher: ^6.1.7
  flutter_riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  equatable: ^2.0.5
  fluttertoast: ^8.2.2
  image_picker: ^1.0.0
  ionicons: ^0.2.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_fonts: ^4.0.4
  dio: ^5.2.1+1
  geolocator: ^9.0.2
  lottie: ^2.5.0
  easy_localization: ^3.0.2
  http: ^0.13.6
  easy_logger: ^0.0.2
  json_serializable: ^6.7.1
  shared_preferences: ^2.0.8


dependency_overrides:
  test_api:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  custom_info_window: ^1.0.1
  link_text: ^0.2.0
  get: ^4.6.5
  location: ^5.0.3
  rive: ^0.11.3
  google_sign_in: ^6.1.6
  firebase_storage: ^11.5.3
  cloud_firestore: ^4.13.3
  flutter_google_places: ^0.3.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/play_store_3.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
 
 
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700

  uses-material-design: true

  assets:
    - assets/
    - assets/RiveAssets/
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/maptheme/aubergine_theme.json
    - assets/maptheme/dark_theme.json
    - assets/images/foursquare.png
    - assets/images/tripadvisor.jpg
    - assets/images/histo.jpeg
    - assets/translations/
